[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "leighsdevblog"
authors = [{name = "Leigh Murray", email = "blogspam@leighmurray.com"}]
dynamic = ["version", "description"]
